### ISSUE TITLE
build script issues fixed upstream

### ISSUE THREAD

**Issue by ryane** [MustWin/kubernetes#5]
Building the binaries and docker images from this branch fail due to two issues that are fixed upstream:
- https://github.com/kubernetes/kubernetes/pull/25973
- https://github.com/kubernetes/kubernetes/commit/cb11324cc32ffc58c022daef3278a0810c675778

**Comment by elg0nz** [comment]
I've merged both into the consul-integration branch for now.
We still need to do some cleanup before merging the consul changes back into master.
